### ISSUE TITLE
Full support of "readOnly" and "writeOnly" keywords from OAS3 spec.

### ISSUE THREAD

**Issue by johnthecat** [koshevy/codegena#17]
In current behavior `readOnly` and `writeOnly` keys simply converts into typescript readonly:
```json
{
  "MyStruct": {
    "properties": {
      "description": {
        "type": "string"
      },
      "id": {
        "readOnly": true,
        "type": "integer"
      },
      "default_role": {
        "writeOnly": true,
        "type": "string"
      }
    },
    "required": [
      "id"
    ],
    "type": "object"
  }
}
```
Converts to
```typescript
interface MyStruct {
    readonly id: number;
    description?: string;
    default_role?: string; // writeOnly flag is ignored
}
```

But [official spec](https://swagger.io/docs/specification/data-models/data-types/) says, that
> You can use the readOnly and writeOnly keywords to mark specific properties as read-only or write-only. This is useful, for example, when GET returns more properties than used in POST – you can use the same schema in both GET and POST and mark the extra properties as readOnly. readOnly properties are included in responses but not in requests, and writeOnly properties may be sent in requests but not in responses.

It means, that TS output for example structure should contain 3 interfaces:
```typescript
// Internal struct, shouldn't be exported
interface MyStruct_Common {
    description?: string;
}

/*
 * Could be empty, if there are no writeOnly fields 
 * (just interface MyStructWritable extends MyStruct_Common {})
 */
export interface MyStructWritable extends MyStruct_Common {
    default_role?: string;
}

export interface MyStruct extends MyStruct_Common {
    readonly id: number;
}
```
Also, all generated request and response bodies must take into account this differences.
POST, PUT, PATCH - writable struct
GET - default struct, as always

**Comment by koshevy** [comment]
Yes, I'm aware of that. Furthermore, I was considering this way (but there was no `writeOnly` in OAS standart). I not sure this is good way.

## Requests

Consider the example of generated request (for POST, PUT and so on) where writable structures are using:

```
/* tslint:disable */
import { HttpErrorBadRequest } from './http-error-bad-request';
import { HttpErrorNotFound } from './http-error-not-found';
import { HttpErrorServer } from './http-error-server';
import { ToDoGroup } from './to-do-group';

export type GetGroupResponse<
  TCode extends 200 | 400 | 404 | 500 = 200 | 400 | 404 | 500,
  TContentType extends 'application/json' = 'application/json'
> = TCode extends 200
  ? TContentType extends 'application/json'
    ? ToDoGroup
    : any
  : TCode extends 400
  ? TContentType extends 'application/json'
    ? HttpErrorBadRequest
    : any
  : TCode extends 404
  ? TContentType extends 'application/json'
    ? HttpErrorNotFound
    : any
  : TCode extends 500
  ? TContentType extends 'application/json'
    ? HttpErrorServer
    : any
  : any;
```

This request uses at least `ToDoGroup`, but can use anonymous structure and other possible variants. We potentially have to have two versions of each of them: writable and read-only. It's very complicate.

What the real value of this feature? Without it developer can understand where is readonly:

- He can see it in definitions
- The value of project is an ability to use JSON Schema for validation at sending and getting. We rather relay to JSON Schemas.

**Comment by koshevy** [comment]
@johnthecat So, if you confident you can implement it without widespread breakdowns — try :)
