### ISSUE TITLE
5 features: path parameter, enumName, CamelCase naming, supertype, main Enum

### ISSUE THREAD

**Issue by stepanzabelin** [koshevy/codegena#28]
Привет. Отличная работа. Спасибо.
Вот чего не хватает для меня (хотя бы опционально)

1) не могу понять почему не генерируются типы для path параметров? это необходимо
2)  В сваггер можно передавать полноценный тип Enum. `@ApiProperty` опция `enumName`. Это позволит избежать повторений перечислений в каждой модели. А также этот Enum  пригодится на фронте. Сейчас этого нет
3) Названия разделенных файлов - CamelCase - что бы название файла соответствовало operationId 
4) Сейчас получается набор типов, который все равно приходится компоновать вручную. Было бы круто иметь супертип, который  описывает данные всего endpoint'a, а еще лучше весь api. пример
`NameSpaceApi['updateUserById']['path'`]   --->   `{
  userId: number
}`
`NameSpaceApi['updateUserById']['body'`]   --->   `{
  userName: string,
 userRole: RoleEnum }`
5) Главный Enum с перечисленными endpoint'ами 
`{  [название метода - operationId] =  [path] }`
Пример `Enum  NameSpaceEndPoint { updateUserById = '/api/updateUser/{id}' }`

**Comment by koshevy** [comment]
Привет, спасибо.

> не могу понять почему не генерируются типы для path параметров? это необходимо
Path-параметры добавлются в общие описания типов параметров, вместе с `query` (а в перспективе, возможно, и с `header`). Например, [вот этот параметр](https://github.com/koshevy/codegena/blob/master/libs/todo-app-scheme/specs/todo-app-spec.json#L536) попадает в [такой интерфейс](https://github.com/koshevy/codegena/blob/master/libs/todo-app-scheme/src/lib/typings/get-group-parameters.ts).

Такой подход был выбран, потому что предполагается, что работа с API будет вестись через генерируемые сервисы, которые будут абстрагировать от лишних деталей. Так, при вызове сервиса, важно только то, обязательные параметры или нет, и какой у них тип данных.

Сейчас уже генерируются [сервисы для Angular](https://github.com/koshevy/codegena/blob/master/libs/todo-app-scheme/src/lib/services/get-group-items.api.service.ts), [на подходе для Axios](https://github.com/koshevy/codegena/blob/feat-axios-wrapper/libs/axios-wrapper/src/lib/prototypes/update-group-item.api.ts). К сожалению, работа идет небыстро, т.к. не хватает времени и рук.

> сваггер можно передавать полноценный тип Enum ...

Вопрос с Enum нужно обсуждать отдельно. По-идее, должны создаваться типы данных, но точно я не помню. Создай, пожалуйста issue на эту тему (просьба, на английском — хотя бы заголовок). Если ты приложишь свои кейсы и результат — это поможет.

> Главный Enum с перечисленными endpoint'ами

Изначально не предполагалась ручная работа с API, этот Enum не будет иметь смысла.
