### ISSUE TITLE
support any mapper for custom types

### ISSUE THREAD

**Issue by balazssoltesz** [koshevy/codegena#46]
In openapi spec there is no type for ObjectId (mongodb). 
Im using WithId<Schema> (from @types/mongodb) type in my controllers which adds an {_id: ObjectId} property to our type defs. 

Is it possible to implement any type mapping solution (ex: based on openapi spec's "format" property) into your generator?
```
"_id": {
  type: "string,
  format: "ObjectId"
} 
```
would be generated as { _id: ObjectId }

sry for my english

**Comment by koshevy** [comment]
Hi! I don't think there is way to use `format` for `WithId`. It looks like a new type definition that may be reused in your specification like [this](https://github.com/koshevy/codegena/blob/master/libs/todo-app-scheme/specs/todo-app-spec.json#L1006).
